### PR TITLE
Issue 15 add GitHub oauth

### PR DESCRIPTION
**Pull request by mgrishko**
## Checklist

- [ ] This commits targets only one specific issue
- [ ] Docs have been added or updated

### CODE REVIEW

**Comment by sobolevn** [comment]
Before going any further, please replace github oauth with gitlab.
It sounds so similar! I always make mistakes in their names.

Ping to review once ready. Thanks so much for participating!

**Comment by mgrishko** [comment]
@sobolevn 
Done!

**Comment by sobolevn** [comment]
@mgrishko can you please fix the CI?

**Comment by mgrishko** [comment]
@sobolevn, hm I don’t know what to assume here, I don’t see any obvious errors in logs. When running locally by config file - all be passing, any guesses?

**Comment by sobolevn** [comment]
The reason in your style:

```
  Code Readability                                                              
┃ 
┃ [R] ↘ The alias `Kira` is not alphabetically ordered among its group.
┃       test/kira_web/controllers/auth_controller_test.exs:5:9 #(KiraWeb.AuthControllerTest)
  Refactoring opportunities                                                     
┃ 
┃ [F] → Pipe chain should start with a raw value.
┃       lib/kira/accounts/queries/user.ex:36 #(Kira.Accounts.Queries.UserQueries.find_or_create_by_email)
Please report incorrect results: https://github.com/rrrene/credo/issues
Analysis took 1.9 seconds (0.07s to load, 1.9s running checks)
191 mods/funs, found 1 refactoring opportunity, 1 code readability issue.
```

**Comment by mgrishko** [comment]
@sobolevn thx, fixed!

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks a lot!

**Pull request merged**
